%% ilustrasjon


hold all
%FV
    %FOV whishbone
    plot3([FOFV(1) FOYV(1) FOBV(1)],... 
          [FOFV(2) FOYV(2) FOBV(2)],...
          [FOFV(3) FOYV(3) FOBV(3)]);
    %FNV Whisbone
    plot3([FNFV(1) FNYV(1) FNBV(1)],... 
          [FNFV(2) FNYV(2) FNBV(2)],...
          [FNFV(3) FNYV(3) FNBV(3)]);
    %Pull rod: Stemmer ikke med hva som er nå
    plot3([FPYV(1) FPIV(1)],...
          [FPYV(2) FPIV(2)],...
          [FPYV(3) FPIV(3)]);
    %rocker
    plot3([FR1V(1) FR2V(1) FR3V(1) FR4V(1) FR1V(1)],...
          [FR1V(2) FR2V(2) FR3V(2) FR4V(2) FR1V(2)],...
          [FR1V(3) FR2V(3) FR3V(3) FR4V(3) FR1V(3)]);
    
    % Instant axis
%     plot3([P_IC_yzPlan_FV(1),Wc_FV(1)] , [P_IC_yzPlan_FV(2),IC_FV(1)] , [P_IC_yzPlan_FV(3) , IC_FV(2)])
%FH
    %FOH wishbone
    plot3([FOFH(1) FOYH(1) FOBH(1)],... 
          [FOFH(2) FOYH(2) FOBH(2)],...
          [FOFH(3) FOYH(3) FOBH(3)]);
    %FNH Whisbone
    plot3([FNFH(1) FNYH(1) FNBH(1)],... 
          [FNFH(2) FNYH(2) FNBH(2)],...
          [FNFH(3) FNYH(3) FNBH(3)]);
      %Pull rod: Stemmer ikke med hva som er nå
    plot3([FPYH(1) FPIH(1)],...
          [FPYH(2) FPIH(2)],...
          [FPYH(3) FPIH(3)]);
    %rocker
    plot3([FR1H(1) FR2H(1) FR3H(1) FR4H(1) FR1H(1)],...
          [FR1H(2) FR2H(2) FR3H(2) FR4H(2) FR1H(2)],...
          [FR1H(3) FR2H(3) FR3H(3) FR4H(3) FR1H(3)]);

%BV
    %BOV whishbone
    plot3([BOFV(1) BOYV(1) BOBV(1)],... 
          [BOFV(2) BOYV(2) BOBV(2)],...
          [BOFV(3) BOYV(3) BOBV(3)]);
    %BNV Whisbone
    plot3([BNFV(1) BNYV(1) BNBV(1)],... 
          [BNFV(2) BNYV(2) BNBV(2)],...
          [BNFV(3) BNYV(3) BNBV(3)]);
    %Pull rod: Stemmer ikke med hva som er nå
    plot3([BPYV(1) BPIV(1)],...
          [BPYV(2) BPIV(2)],...
          [BPYV(3) BPIV(3)]);
    %rocker
    plot3([BR1V(1) BR2V(1) BR3V(1) BR4V(1) BR1V(1)],...
          [BR1V(2) BR2V(2) BR3V(2) BR4V(2) BR1V(2)],...
          [BR1V(3) BR2V(3) BR3V(3) BR4V(3) BR1V(3)]);
   

%BH
    %BOH wishbone
    plot3([BOFH(1) BOYH(1) BOBH(1)],... 
          [BOFH(2) BOYH(2) BOBH(2)],...
          [BOFH(3) BOYH(3) BOBH(3)]);
    %BNH Whisbone
    plot3([BNFH(1) BNYH(1) BNBH(1)],... 
          [BNFH(2) BNYH(2) BNBH(2)],...
          [BNFH(3) BNYH(3) BNBH(3)]);
    %Pull rod:
    plot3([BPYH(1) BPIH(1)],...
          [BPYH(2) BPIH(2)],...
          [BPYH(3) BPIH(3)]);
    %rocker
    plot3([BR1H(1) BR2H(1) BR3H(1) BR4H(1) BR1H(1)],...
          [BR1H(2) BR2H(2) BR3H(2) BR4H(2) BR1H(2)],...
          [BR1H(3) BR2H(3) BR3H(3) BR4H(3) BR1H(3)]);
      
%Roll axis
plot3([RC_F(1) RC_B(1)] ,...
      [RC_F(2) RC_B(2)] ,...
      [RC_F(3) RC_B(3)]);
  
% Stearing system
plot3([UHV(1) SRV(1) SRH(1) UHH(1)] , ...
      [UHV(2) SRV(2) SRH(2) UHH(2)] , ...
      [UHV(3) SRV(3) SRH(3) UHH(3)]);
%style
    grid on 
    axis equal
    rotate3d on